cat: cat.c echo
	gcc cat.c -o ../cat

echo: echo.c ls
	gcc echo.c -o ../echo

ls: ls.c pwd
	gcc ls.c -o ../ls

pwd: pwd.c mv
	gcc pwd.c -o ../pwd

mv:mv.c rm
	gcc mv.c -o ../mv

rm: rm.c mkdir
	gcc rm.c -o ../rm

mkdir:mkdir.c wc
	gcc mkdir.c -o ../mkdir

wc: wc.c grep
	gcc wc.c -o ../wc

grep: grep.c clear
	gcc grep.c -o ../grep

clear: clear.c
	gcc clear.c -o ../clear